### ISSUE TITLE
Restrictions set with the Channels command are not respected

### ISSUE THREAD

**Issue by fverdoja** [lexicalunit/spellbot#290]
**Describe the bug**
I have set the bot to be active only on one channel with the `!spellbot channels` command but it still replies to `!lfg` requests (and others) on any other channel it has access to.

**To Reproduce**
1. Invite the bot leaving it able to access any channel
2. As an admin, use `!spellbot channels #channel_A` to have it only active on that one channel
3. Go to `#channel_B` and issue any command (e.g., `!lfg`)
4. The bot will reply opening a new game in the channel.

**Expected behavior**
The bot should reply to commands (e.g., `!lfg`) only on the channels set by the `!spellbot channel` command (in this case, only `#channel_A`)

**Screenshots**
Current config:
![image](https://user-images.githubusercontent.com/19264446/100726481-a9804480-33cd-11eb-8656-617a6a007cdc.png)
Issuing a `!lfg` from the `#test` channel:
![image](https://user-images.githubusercontent.com/19264446/100726637-dfbdc400-33cd-11eb-8bcc-43510f293c39.png)

**Discord version:**
> Stable 72430 (15026f7)
> Host 0.0.308
> Windows 10 64-Bit (10.0.19041)

**Comment by lexicalunit** [comment]
Thanks for the issue @fverdoja!

I think what's happening here is that SpellBot will always respond to the server owner or anyone with server admin permissions. This is to ensure that owners/admins can always access SpellBot. I had an issue where an admin accidentally locked themselves out of using the bot because they set their `!spellbot channels` to a channel and then deleted that channel. They had no way of getting SpellBot working again because it wouldn't respond to them in any other channel.

If you want to specifically prevent SpellBot from being in a channel you can also use Discord channel permissions. Click the cog next to the channel to edit its setting and then go in the the `Permissions` tab. Click the `+` button next to `Roles/Members` and select SpellBot. Select SpellBot and in the right panel disable `Read Messages`. Finally click the `Save Changes` button.

![Screen Shot 2020-12-01 at 1 11 48 PM](https://user-images.githubusercontent.com/1903876/100797331-ccfbbd00-33d6-11eb-944f-c689c6741e8d.png)

Now when you go to that channel you should not see SpellBot in members list on the far right panel of Discord. SpellBot will not function within that channel anymore, even for owners and admins.

Does this help resolve this issue for you?

**Comment by fverdoja** [comment]
Hi,
Thank you for your answer. It fine if it only work for the server owner. I didn't think that to be the case so I thought the other user might invoke it by mistake in the wrong channel. You description definitively solves the issue.
Thanks.
