### ISSUE TITLE
Support beta/prod options

### ISSUE THREAD

**Issue by lexicalunit** [lexicalunit/spellbot#36]
This is blocked until we get support from SpellTable on their backend so that the API endpoint can indicate beta/prod.

**Describe the solution you'd like**

- Configurable at server level?
- Something you pick with a tag when you issue the !play command?
- Matchmaking between people that want prod and people that want beta?
- Something based on a user preference?

**Comment by ekloswick** [comment]
Would it be possible to have this just be an automatic text replacement for the provided link? Say if you type "!lfg beta" or something, the link can be created as normal, but then the bot just swaps the "www" for "beta". This already works if you manually replace the prefix in the URL, this would just be a QOL update.

**Comment by lexicalunit** [comment]
@ekloswick Yep that could work so long as the beta site's URL remains the same except for the replacement of `www` with `beta`.

I was thinking of making this something that server admins could configure on a channel level maybe? It's a bit hard to do at the user level.

Like let's say for example Player A wants to use beta, so they do something like `!use-beta` so whenever they do a `!lfg` they will get links with `beta.[...]` in them. But what now happens if someone else who doesn't want to use beta is put into their game? AFAIK either all players have to be on the beta site or all players have to be on the production site. You can't mix and match. That's why I was thinking it'd have to be at the channel level. Like an admin could configured the bot so that all links in `#some-channel` show up as beta links.

Thoughts?

**Comment by ekloswick** [comment]
@lexicalunit True, it's all-or-nothing for beta/non-beta. If you go user-level, it may be fine to have it be a per-lobby thing, so whoever initiates the !lfg ("host") would be the decider, and the beta/non-beta nature of the lobby could be specified in some way on the SpellBot lobby post. For admin-level, per channel/server could also work.

From my usage, overall I don't think people mind which version is used from game to game, though the few users I've run into that have expressed an opinion have always been pro-beta. Having the "host" have the option of which to default to seems like the best way to go, assuming the implementation of user preferences isn't too large a burden.

**Comment by lexicalunit** [comment]
Having it on the user could lead to feelbads and really complicated matchmaking logic tho. Imagine this scenario:

```
Player A: !spellbot user-options use-beta

**sometime later, maybe in a different channel**

Player A: !lfg
SpellBot: [ game post ]

Player B: !lfg
SpellBot: [ Doesn't put player B into the game with Player A b/c Player B hasn't opted-in to beta ]
SpellBot: [ Creates a new game post maybe, with just Player B in it? ]

Player B: **Reacts with 🤚 to player A's game post**
SpellBot: [ Ignores the reaction because Player B can't join a beta game ]
SpellBot: [ Creates a new game post maybe, with just Player B in it? ]
```

So now Player B feelsbad b/c they don't know why they can't join the game. If they're the only person in the channel who isn't set up to use beta then they'll get really frustrated b/c they won't be able to join any games, and no one will be joining their games either.

And there's a ton of logic SpellBot has to do, making sure that if matches players to games correctly based on beta vs www.

It'd be a lot easier to do at the channel level b/c then it's literally just a a couple lines of code to change:

```
if channelOptions.useBeta:
    spellTableLink.replace("www", "beta", 1)
```

**Comment by ekloswick** [comment]
Oh, there are joining restrictions based on whether the lobby is beta or not? I was thinking SpellBot just has a lobby, and whether or not the link it spits out is beta doesn't matter to those signing up - they're just joining a lobby, regardless of their personal user host preference. If that extra functionality is needed to restrict what lobbies users can join, then yeah, that scenario would be a problem.

If the channel method is easier/quicker overall, it'd still be fine, since I think most servers using it would have an overall preference one way or the other and could set it for the group appropriately (and like you mentioned, split out into two channels if the need is really there).

For the user-level option, I was just thinking what would be easier for users who prefer beta (i.e. not the norm) who would then have an avenue they could pursue without admin intervention, rather than leave it as a mod/channel option (thinking in a moderately sized+ server). Of course, that same individual enablement could also just be a command argument that they just put in each time ("!lfg -beta").

I guess it comes down to if/how lobby joining restrictions are implemented.

**Comment by lexicalunit** [comment]
Note: This can be a toggle option in guild settings in v7.

**Comment by lexicalunit** [comment]
beta.spelltable.wizards.com is no longer a thing.

**Comment by ekloswick** [comment]
beta.spelltable.com is still up, for what it's worth.

**Comment by lexicalunit** [comment]
Oh there it is!
