### ISSUE TITLE
Letting the bot create a discord room directly after joining of second player

### ISSUE THREAD

**Issue by Dalliboy** [lexicalunit/spellbot#457]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when  people just sit and wait without possibility to chat and describe what they are up to. This is not an HOT issue but it defineltley annoyed me everytime i get in search for new players in several servers
 useing your Spellbot.

**Describe the solution you'd like**
So i don´t know if it´s technically possible to start the chat channel right away when the second player joins the que.
For my server i also wanted to create a fix radio channel that would be streamed off my computer. Would be a nice option.  

**Describe alternatives you've considered**
Maybe something like fixed audio pools for different roles would be an option.  

**Additional context**
I have some basics in programming (self made courses on sololearn) To be honest i forgot already most of it. I wanted to specialize on UI and humanizing automaed Robotics .

**Comment by lexicalunit** [comment]
Hey @Dalliboy, thanks for your interest in SpellBot!

Do you mean the voice channel that SpellBot creates?

I think that make sense... like after the 2nd person joins, that's when it creates the voice channel. So the people waiting for more to join can join the voice channel and chat while they wait. Did I get that right?

One issue I can think of is that some servers have it set so that the voice channel is only shown in Direct Messages, and the bot doesn't send a Direct Message until the game starts.

But this does seem like an interesting idea that could maybe be a configuration option.

**Comment by Dalliboy** [comment]
Hi There,

yes that´s the point. I think it can be fun Option to caht right away and also welcome new Players. The comunication is the most importatnt part and very often players just skip this and start with 7 cards. Maybe this cannot fit all servers but I would welcome it on my.

Second (not so importatnt) thing is if there is possibility to connect an fixed radio server on the voice channel as a background music. Or this must be programmed somehow on Discord eval. 

Thank you for your quick response. Do you have more stuuf going on? Some other projectts I mean.

**Comment by lexicalunit** [comment]
Note to self: This could now be added to guild configuration of SpellBot in version 7.
