### ISSUE TITLE
Discord Thread Support For All Commands

### ISSUE THREAD

**Issue by wise-io** [lexicalunit/spellbot#681]
**Describe the bug**
Some SpellBot commands do not work inside of Discord Threads.

**To Reproduce**
1. Go to a thread.
2. Use `/lfg`
3. See error

**Expected behavior**
Commands function as normal within a Discord Thread.

**Comment by lexicalunit** [comment]
Ah,I see why this happens. SpellBot uses discord channels for match making and settings. Each channel can have its own default settings (player seats, game format, etc...) and people using `/lfg` are only matched against other people in the same channel.

Sadly, the way Discord handles threads is that they are, behind the scenes, their own channel with their own channel ID and everything. That means SpellBot would only be able to match people against other people using `/lfg` in the same thread. They wouldn't be matched with people in the parent channel. That seems not ideal.

I should be able to get the parent ID, the ID of the channel, from the thread using `discord.py`: https://discordpy.readthedocs.io/en/master/api.html?highlight=thread#discord.Thread.parent_id

However this support is only available in version 2.0. That's unfortunate because `discord.py` was abandoned before 2.0 was released. So it's in an incomplete state. I am also using `discord-interactions`v3 which does not support the latest version of `discord.py` (what people are calling 2.0 despite it not being officially released).

The `discord-interactions` team is already planning on releasing a v4 which will support this `discord.py` "version 2.0" library. Once they do that, and I migrate my code from their v3 API to their new v4 API, then I can upgrade `discord.py` to a version that properly supports Threads.

All that is to say: I can't fix this right now, but I will hopefully be able to fix it in the future!

**Comment by lexicalunit** [comment]
Now that I've begun porting over code to discord 2.0, this actually seems like it will be huge effort to make work.
