### ISSUE TITLE
Schedule a Game in the Future

### ISSUE THREAD

**Issue by wise-io** [lexicalunit/spellbot#683]
**Is your feature request related to a problem? Please describe.**
Sometimes, you want to plan ahead and do an `/LFG` for a future time/date.

**Describe the solution you'd like**
Add a subcommand/option to the `/LFG` command, allowing users to schedule a game in the future.
Support for the following would be great:
- [Discord Scheduled Events](https://support.discord.com/hc/en-us/articles/4409494125719-Scheduled-Events)
- [Epoch Timestamps](https://pastebin.com/rJFE9yxq) (for coordinating between different time zones)
- Allowing Organizer to change date/time of game (reschedule)
- Sending reminders ~15 minutes (customizable) before scheduled game to interested members
- Link to spectate the scheduled game (if public links are enabled)

**Comment by lexicalunit** [comment]
Unfortunately the [`discord.py`](https://github.com/Rapptz/discord.py) library I use to implement SpellBot doesn't currently support Scheduled Events and is no longer maintained so it likely won't be getting support for them any time soon. There's 3 alternatives right now that I am keeping my eye on in terms of future development:

- https://github.com/nextcord/nextcord
- https://github.com/Pycord-Development/pycord
- https://github.com/goverfl0w/discord-interactions

It's not yet clear to me which one of these I should go with as the dust is still settling from the death of `discord.py`. It's possible that support for Scheduled Events may be added via one of these three libraries at some point though.

The alternative then is for SpellBot to implement events itself somehow. This is similar to what [Apollo Bot](https://apollo.fyi/) does. And Apollo already does this feature really well so I wonder if people would be better served by just using that, rather than have me implement it within SpellBot too.
